export const {
  VUE_APP_BASE_API_URL,
  VUE_APP_AZURE_SUBSCRIPTION,
  VUE_APP_URL_RESOURCE,
  VUE_APP_TIME_ZONE,
  VUE_APP_ZOOM_OAUTH_ACCOUNT_ID,
  VUE_APP_ZOOM_OAUTH_CLIENT_ID,
  VUE_APP_ZOOM_OAUTH_CLIENT_SECRET,
  VUE_APP_ZOOM_CLIENT_ID,
  VUE_APP_ZOOM_CLIENT_SECRET,
} = process.env;
